"""image_id deleted

Revision ID: 08bdd6c1f16e
Revises: 861fde023449
Create Date: 2024-02-23 18:06:58.759569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bdd6c1f16e'
down_revision: Union[str, None] = '861fde023449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
