"""events model updated

Revision ID: 24b2264d9e37
Revises: ed7d9c3e021e
Create Date: 2024-02-23 12:22:41.445626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24b2264d9e37'
down_revision: Union[str, None] = 'ed7d9c3e021e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_type',
               existing_type=postgresql.ENUM('concert', 'museum', 'exhibition', 'other', name='eventtypeenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'event_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('concert', 'museum', 'exhibition', 'other', name='eventtypeenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
