"""people amount added to events

Revision ID: 6dc127c2fd25
Revises: 9c00b8f0f283
Create Date: 2024-02-16 13:02:13.751357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc127c2fd25'
down_revision: Union[str, None] = '9c00b8f0f283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('people_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'people_amount')
    # ### end Alembic commands ###
