"""update events

Revision ID: 9c00b8f0f283
Revises: 1f84224cd144
Create Date: 2024-02-16 12:05:52.501842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c00b8f0f283'
down_revision: Union[str, None] = '1f84224cd144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
