"""location added to tickets

Revision ID: d1c4a1f15540
Revises: 6dc127c2fd25
Create Date: 2024-02-17 17:33:30.067196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c4a1f15540'
down_revision: Union[str, None] = '6dc127c2fd25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('location', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'location')
    # ### end Alembic commands ###
