"""Tickets model updated

Revision ID: ed7d9c3e021e
Revises: d7e93035f1aa
Create Date: 2024-02-22 12:50:28.697529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed7d9c3e021e'
down_revision: Union[str, None] = 'd7e93035f1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'event_type',
               existing_type=postgresql.ENUM('concert', 'museum', 'exhibition', 'other', name='eventtypeenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'event_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('concert', 'museum', 'exhibition', 'other', name='eventtypeenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
