version: '3.7'
services:
  db:
    container_name: postgres_events_booking
    image: postgres:latest
    env_file:
      - .env-non-dev
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis_events_booking
    ports:
      - "6379:6379"

  events_booking:
    build:
      context: .
    container_name: events_booking_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/events_booking/docker/app.sh"]
#    command: sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 7777:8000

  celery:
    build:
      context: .
    container_name: celery_events_booking
    command: ["/events_booking/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: flower_events_booking
    command: [ "/events_booking/docker/celery.sh", "flower" ]
    env_file:
      - .env-non-dev
    ports:
      - 5555:5555
    depends_on:
      - redis

volumes:
  postgresdata: